version: '3.8'
services:
    web-app-prom:
        build: ./core
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
          - ./core:/usr/src/app/
        ports:
          - 8000:8000
        env_file:
          - ./.env
        depends_on:
             - database-prom
    database-prom:
        image: postgres:14.6-alpine
        volumes:
          - postgres_volume:/var/lib/postgresql/data/
        environment:
           - POSTGRES_DB=postgres
           - POSTGRES_USER=postgresUSER
           - POSTGRES_PASSWORD=postgresPASS
volumes:
 postgres_volume: