######################
#  server ipromouter #
######################

server {
        server_name btlplus.ru www.btlplus.ru xn----btb4abjbeix.xn--p1ai www.xn----btb4abjbeix.xn--p1ai;
        listen 443 ssl http2;

        root  /home/alice/ipromouter/core;
        charset UTF-8;

        gzip on;
        gzip_disable "msie6";
        gzip_vary on;
        gzip_proxied any;
        gzip_comp_level 6;
        gzip_buffers 16 8k;
        gzip_http_version 1.1;
        gzip_min_length 256;
        gzip_types
                application/atom+xml
                application/geo+json
                application/javascript
                application/x-javascript
                application/json
                application/ld+json
                application/manifest+json
                application/rdf+xml
                application/rss+xml
                application/xhtml+xml
                application/xml
                font/eot
                font/otf
                font/ttf
                image/svg+xml
                text/css
                text/javascript
                text/plain
                text/xml;

        # Статические файлы
        location ~ ^/(assets|static)/ {
            expires 30d;
            add_header Cache-Control "public, max-age=2592000, immutable";
        }

         # Медиа файлы
        location ~ ^/media/ {
            expires 30d;
            add_header Cache-Control "public, max-age=2592000";
        }

        # Изображения
        location ~ ^/images/ {
            expires 30d;
            add_header Cache-Control "public, max-age=2592000";
        }

        location /robots.txt  {
            root  /home/alice/ipromouter/core;
        }

        # Favicon
        location ~ ^/favicon\.(ico|svg)$ {
            expires 30d;
            add_header Cache-Control "public, max-age=2592000";
        }

        # Основной проксь (приложение)
        location / {
            proxy_pass http://127.0.0.1:8000;
            proxy_set_header Host $server_name;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_http_version 1.1;
            proxy_set_header Connection "";

            # Таймауты
            proxy_connect_timeout 60s;
            proxy_send_timeout 60s;
            proxy_read_timeout 60s;
        }


        error_page 500 502 503 504 /500.html;
        location = /500.html {
            root  /home/alice/ipromouter/core/app_site/templates;
        }
        # Запретить доступ к чувствительным файлам
        location ~ /\. {
            deny all;
            access_log off;
            log_not_found off;
        }

        keepalive_timeout  65;
}

server {

        server_name   btlplus.ru  www.btlplus.ru xn----btb4abjbeix.xn--p1ai www.xn----btb4abjbeix.xn--p1ai;
        listen 80;
        return 404;
}